import type { ProcessedResult } from "./processor.js"
import type { ComponentEntry } from "./crawler.js"

/**
 * Generates App.tsx for the react-app.
 * Handles two cases:
 *  - preBundledNames: components already bundled by server → import directly, no npx unframer needed
 *  - remaining: show TODO comment
 */
export function buildAppScaffold(
  manifest: any,
  mergedComponents: Record<string, string>,
  componentEntries: ComponentEntry[],
  processed: ProcessedResult,
  preBundledNames: string[] = [],
): string {
  const {
    projectId = "",
    projectName = "Framer Site",
    rawEntries = [],
    layout = [],
  } = manifest

  const preBundledSet = new Set(preBundledNames)
  const hasPreBundled = preBundledSet.size > 0
  // Also check old-style /modules/ URLs (resolvable via npx unframer)
  const moduleUrlComponents = Object.entries(mergedComponents)
    .filter(([, url]) => url.includes("/modules/") && url.endsWith(".js"))
    .map(([name]) => name)
  const hasModuleUrls = moduleUrlComponents.length > 0
  const componentNames: string[] = rawEntries.map((e: any) => e.name as string)

  const setupCmd = hasPreBundled
    ? "npm install"
    : hasModuleUrls ? "npx unframer" : `npx unframer ${projectId}`

  // Build imports — pre-bundled components can be imported directly
  const importLines = [
    ...preBundledNames.map(name => `import ${toPascalCase(name)} from "./framer/${sanitizePath(name)}"`),
    ...moduleUrlComponents.filter(n => !preBundledSet.has(n))
      .map(name => `import ${toPascalCase(name)} from "./framer/${sanitizePath(name)}"`)
  ].join("\n")

  // All importable components
  const importableSet = new Set([...preBundledNames, ...moduleUrlComponents])

  const orderedNames: string[] = layout.length > 0
    ? [...layout].sort((a: any, b: any) => (a.top ?? 0) - (b.top ?? 0)).map((s: any) => s.name ?? s.componentName)
    : componentNames

  const jsxSections = orderedNames
    .filter((n: string) => n && n.trim())
    .map((name: string) => {
      const safe = toPascalCase(name)
      if (importableSet.has(name)) {
        const tag = preBundledSet.has(name) ? `<${safe} />` : `<${safe} />`
        const note = preBundledSet.has(name) ? "pre-bundled" : "via unframer"
        return `      ${tag} {/* ${name} — ${note} */}`
      }
      return `      {/* TODO: ${name} — run: ${setupCmd} */}`
    })
    .join("\n")

  const componentList = componentNames.map(n => `//   • ${n}${preBundledSet.has(n) ? " ✓ pre-bundled" : ""}`).join("\n")

  return `// Auto-generated by Framer Auto Export
// ${new Date().toISOString()}
// Project: ${projectName} (${projectId})
//
// ═══════════════════════════════════════════════════════
//  SETUP — run these commands in this folder:
//
//    ${setupCmd === "npm install" ? "npm install\n//    npm run dev" : `npm install\n//    ${setupCmd}\n//    npm run dev`}
//
// ═══════════════════════════════════════════════════════
//
// Components (${componentNames.length} total):
${componentList}
//
// Pre-bundled by server: ${preBundledSet.size}/${componentNames.length}

import "./framer/styles.css"
${importLines || `// Run: ${setupCmd} to download components`}

export default function App() {
  return (
    <main style={{ width: "100%", minHeight: "100vh" }}>
${jsxSections || componentNames.map(n => `      {/* ${n} — run ${setupCmd} first */}`).join("\n")}
    </main>
  )
}
`
}

function toPascalCase(name: string): string {
  return name.replace(/[^a-zA-Z0-9 _/-]/g, "")
    .split(/[\s_/-]+/).filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("") || "Component"
}

function sanitizePath(name: string): string {
  return toPascalCase(name)
}
